# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }
"""
GenClash Arena - Intelligent Contract for GenLayer
================================================
Showcases:
  * Optimistic Democracy consensus on subjective AI judgements (XP scoring).
  * Native LLM access via gl.nondet.exec_prompt for weekly theme generation.
  * Payable entry fee in GEN.
  * On-chain leaderboard for weekly XP distribution.

Mission requirements covered:
  - Multiplayer-ready (rooms keyed by address; can be extended to PvP).
  - Match length 5-15 min (tracked via duration_seconds field).
  - Replayable weekly: weekly_theme is regenerated by validators using LLMs.
  - Leaderboard with XP for community ranking.
"""

from genlayer import *

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Entry fee = 0.001 GEN (in wei). Adjust before deployment if desired.
ENTRY_FEE_WEI: int = 10**15

# XP awarded must stay in this absolute band (sanity bound for the AI judge).
MAX_XP_PER_MATCH: int = 100

# Acceptable spread between leader and validator scoring (Comparative
# Equivalence Principle margin). Validators accept the leader's XP if their
# own AI evaluation is within +/- this many points.
XP_VALIDATION_MARGIN: int = 12


class GenClashArena(gl.Contract):
    # ---- Persistent storage ----------------------------------------------
    owner: Address

    # Address -> 1 if a paid-but-not-yet-consumed session exists, else 0.
    paid_sessions: TreeMap[Address, u256]

    # Address -> total XP earned across all matches.
    xp: TreeMap[Address, u256]

    # Address -> number of finalized matches recorded.
    match_count: TreeMap[Address, u256]

    # Light-weight leaderboard index: every address that has ever earned XP.
    # Ordering / top-N is computed off-chain by the frontend (cheaper).
    players: DynArray[Address]

    # Weekly content (replayability): regenerated via LLM consensus.
    current_week: u256
    weekly_theme: str

    total_matches: u256
    total_fees_collected: u256

    # ---- Constructor ------------------------------------------------------
    def __init__(self) -> None:
        self.owner = gl.message.sender_address
        self.current_week = u256(0)
        self.weekly_theme = (
            "Week 0 - Classic Neon Hockey: standard pucks, standard paddles, "
            "standard glory."
        )
        self.total_matches = u256(0)
        self.total_fees_collected = u256(0)

    # ---- Optional sponsor tip (free to play; any payable value accepted) -
    @gl.public.write.payable
    def pay_to_play(self) -> None:
        """Optional sponsor tip. Any value (including zero) is accepted and
        recorded as an active session so the player can submit results.
        Kept as a legacy entrypoint for frontends that want to show a tip UI.
        """
        sender = gl.message.sender_address
        self.paid_sessions[sender] = u256(1)
        if int(gl.message.value) > 0:
            self.total_fees_collected = u256(
                int(self.total_fees_collected) + int(gl.message.value)
            )

    # ---- Match result submission (AI-judged via Optimistic Democracy) ----
    @gl.public.write
    def record_result(
        self,
        player_score: int,
        ai_score: int,
        level: int,
        duration_seconds: int,
        player_summary: str,
    ) -> None:
        """Submit a finished match. Validators run the GenClash Arena match judgement
        independently; consensus is reached when their XP scores are within
        XP_VALIDATION_MARGIN of the leader's score.
        """
        player = gl.message.sender_address
        # Free to play: no entry fee required, no session gating.
        # Anyone can submit a match result; the AI judge decides the XP.

        # Sanitize inputs (defense in depth - GenVM also enforces types).
        ps = max(0, min(99, int(player_score)))
        ascore = max(0, min(99, int(ai_score)))
        lvl = max(1, min(50, int(level)))
        dur = max(0, min(60 * 60, int(duration_seconds)))
        summary = (player_summary or "")[:500]
        theme = self.weekly_theme

        prompt = f"""
You are the official judge for GenClash Arena, a neon air-hockey arcade running on
the GenLayer blockchain. Award fair XP (0..{MAX_XP_PER_MATCH}) for one match.

Weekly theme: {theme}
Level played: {lvl}
Final score: player {ps} - AI {ascore}
Match duration (seconds): {dur}
Player self-report (untrusted text): "{summary}"

Scoring guidelines (be deterministic about these rules):
  * Win  (player > AI): base 50 XP.
  * Tie  (player == AI): base 20 XP.
  * Loss (player < AI): base 10 XP.
  * +3 XP per level above 1 (capped at +30).
  * +4 XP per goal of margin in a win (capped at +20).
  * -15 XP if duration < 30 (suspicious speed-run).
  * Set XP to 0 if the self-report mentions cheating, hacks, exploits, or
    abusive content.
  * Final XP must be clamped to [0, {MAX_XP_PER_MATCH}].

Respond strictly as compact JSON: {{"xp": <int>, "reason": "<<=80 chars>"}}.
"""

        def leader_fn() -> dict:
            return gl.nondet.exec_prompt(prompt, response_format="json")

        def validator_fn(leader_result) -> bool:
            if not isinstance(leader_result, gl.vm.Return):
                return False
            try:
                leader_xp = int(leader_result.calldata["xp"])
            except Exception:
                return False
            if leader_xp < 0 or leader_xp > MAX_XP_PER_MATCH:
                return False
            try:
                mine = leader_fn()
                my_xp = int(mine["xp"])
            except Exception:
                return False
            return abs(leader_xp - my_xp) <= XP_VALIDATION_MARGIN

        verdict = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)
        awarded = max(0, min(MAX_XP_PER_MATCH, int(verdict["xp"])))

        # Update state (deterministic - safe outside nondet).
        prior = int(self.xp.get(player, u256(0)))
        if prior == 0:
            self.players.append(player)
        self.xp[player] = u256(prior + awarded)

        self.match_count[player] = u256(
            int(self.match_count.get(player, u256(0))) + 1
        )
        self.total_matches = u256(int(self.total_matches) + 1)

    # ---- Weekly theme rotation (LLM generated) ---------------------------
    @gl.public.write
    def refresh_weekly_theme(self) -> None:
        """Anyone can trigger a weekly theme refresh. Validators must agree
        the new theme is well-formed and non-abusive (non-comparative EP).
        """
        prompt = (
            "Generate a fun weekly modifier for GenClash Arena, a neon air-hockey "
            "arcade game. Must be safe-for-work, under 140 characters, and "
            "evocative of a gameplay twist (e.g. 'low gravity', 'fog of war', "
            "'double puck mayhem'). Respond strictly as JSON: "
            '{"theme": "Week N - <Title>: <one sentence>"}.'
        )

        def leader_fn() -> dict:
            return gl.nondet.exec_prompt(prompt, response_format="json")

        def validator_fn(leader_result) -> bool:
            if not isinstance(leader_result, gl.vm.Return):
                return False
            theme = leader_result.calldata.get("theme", "")
            if not isinstance(theme, str):
                return False
            if not (10 <= len(theme) <= 200):
                return False
            banned = ("nsfw", "kill", "racist", "slur")
            low = theme.lower()
            return not any(b in low for b in banned)

        out = gl.vm.run_nondet_unsafe(leader_fn, validator_fn)
        self.weekly_theme = str(out["theme"])[:200]
        self.current_week = u256(int(self.current_week) + 1)

    # ---- Read-only views -------------------------------------------------
    @gl.public.view
    def has_paid(self, player_hex: str) -> bool:
        addr = Address(player_hex)
        return int(self.paid_sessions.get(addr, u256(0))) > 0

    @gl.public.view
    def get_xp(self, player_hex: str) -> int:
        addr = Address(player_hex)
        return int(self.xp.get(addr, u256(0)))

    @gl.public.view
    def get_match_count(self, player_hex: str) -> int:
        addr = Address(player_hex)
        return int(self.match_count.get(addr, u256(0)))

    @gl.public.view
    def get_weekly_theme(self) -> str:
        return self.weekly_theme

    @gl.public.view
    def get_current_week(self) -> int:
        return int(self.current_week)

    @gl.public.view
    def get_total_matches(self) -> int:
        return int(self.total_matches)

    @gl.public.view
    def get_player_count(self) -> int:
        return len(self.players)

    @gl.public.view
    def get_leaderboard(self) -> list:
        """Return [(address_hex, xp), ...] for off-chain ranking."""
        out: list = []
        for addr in self.players:
            out.append((str(addr), int(self.xp.get(addr, u256(0)))))
        return out
